"""Serve web/ on localhost and open the viewer.

Static files only. The binaries are large enough that the default
SimpleHTTPRequestHandler's per-request logging gets noisy, so it is
quietened, and threading is enabled so the two data fetches overlap.
"""
from __future__ import annotations

import argparse
import http.server
import socketserver
import threading
import webbrowser
from pathlib import Path

WEB = Path(__file__).resolve().parent / "web"


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=str(WEB), **kw)

    def log_message(self, fmt, *args):  # noqa: A002 - stdlib signature
        pass

    def end_headers(self):
        # The data files are regenerated by prepare.py; never let a stale
        # copy survive in the browser cache.
        self.send_header("Cache-Control", "no-store")
        super().end_headers()


class Server(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--port", type=int, default=8412)
    ap.add_argument("--no-open", action="store_true")
    args = ap.parse_args()

    if not (WEB / "data" / "meta.json").exists():
        raise SystemExit("no web/data/meta.json — run `python3 prepare.py` first")

    url = f"http://localhost:{args.port}/"
    with Server(("127.0.0.1", args.port), Handler) as httpd:
        print(f"desiview on {url}   (ctrl-c to stop)")
        if not args.no_open:
            threading.Timer(0.4, webbrowser.open, [url]).start()
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print()


if __name__ == "__main__":
    main()
