"""Serve the viewer on localhost and open it in a browser."""
from __future__ import annotations

import http.server
import socketserver
import threading
import webbrowser
from pathlib import Path

from .prepare import default_cache, find_catalog, is_current, prepare, ZMAX, ZMIN

TEMPLATES = Path(__file__).resolve().parent / "templates"
DEFAULT_PORT = 8412


def _handler_for(cache: Path):
    """Static handler serving the templates, with /data from the cache."""

    class Handler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *a, **kw):
            super().__init__(*a, directory=str(TEMPLATES), **kw)

        def translate_path(self, path):
            clean = path.split("?", 1)[0].split("#", 1)[0]
            if clean.startswith("/data/"):
                # Resolve inside the cache and refuse anything that
                # escapes it, so a crafted path cannot read the disk.
                target = (cache / clean[len("/data/"):]).resolve()
                if cache.resolve() in target.parents or target == cache.resolve():
                    return str(target)
                return str(cache / "_denied")
            return super().translate_path(path)

        def end_headers(self):
            # The binaries are regenerated by prepare(); never let a stale
            # copy survive in the browser cache.
            self.send_header("Cache-Control", "no-store")
            super().end_headers()

        def log_message(self, fmt, *args):  # noqa: A002 - stdlib signature
            pass

    return Handler


class _Server(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


def view(catalog=None, cache=None, zmin=ZMIN, zmax=ZMAX, port=DEFAULT_PORT,
         browser=True, rebuild=False, quiet=False):
    """Open the 3D source-distribution viewer.

    Packs the catalogue on first use and whenever it has changed, then
    starts a local HTTP server and blocks until interrupted (Ctrl+C).

    Parameters
    ----------
    catalog : str or Path, optional
        DESI QSO regions catalogue. Located automatically when omitted:
        ``$DESIVIEW_CATALOG``, the working directory, then a sibling
        ``datastore/``.
    cache : str or Path, optional
        Where packed binaries live. Defaults to ``~/.cache/desiview``,
        or ``$DESIVIEW_CACHE``.
    zmin, zmax : float
        Redshift range to pack. Default 0.8-3.5.
    port : int
        Port to serve on. Default 8412.
    browser : bool
        Open the system browser automatically. Default True.
    rebuild : bool
        Re-pack even if the cache is already current.
    """
    cache = Path(cache).expanduser() if cache else default_cache()
    catalog = Path(catalog).expanduser() if catalog else find_catalog()

    if rebuild or not is_current(cache, catalog, zmin, zmax):
        prepare(catalog, cache, zmin=zmin, zmax=zmax, quiet=quiet)
    elif not quiet:
        print(f"using packed catalogue in {cache}")

    url = f"http://localhost:{port}/"
    with _Server(("127.0.0.1", port), _handler_for(cache)) as httpd:
        if not quiet:
            print(f"desiview on {url}   (ctrl-c to stop)")
        if browser:
            threading.Timer(0.4, webbrowser.open, [url]).start()
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            if not quiet:
                print()
